/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BoardStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "boardCount"
      | "boards"
      | "bountySubmissions"
      | "signerAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "boardCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "boards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountySubmissions",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "boardCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountySubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
}

export interface BoardStorage extends BaseContract {
  connect(runner?: ContractRunner | null): BoardStorage;
  waitForDeployment(): Promise<this>;

  interface: BoardStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  boardCount: TypedContractMethod<[], [bigint], "view">;

  boards: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;

  bountySubmissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;

  signerAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "boardCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "boards"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountySubmissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "signerAddress"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
