/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BoardView {
  export type BoardViewStructStruct = {
    id: BigNumberish;
    creator: AddressLike;
    name: string;
    description: string;
    img: string;
    totalPledged: BigNumberish;
    createdAt: BigNumberish;
    rewardToken: AddressLike;
    closed: boolean;
    config: string;
  };

  export type BoardViewStructStructOutput = [
    id: bigint,
    creator: string,
    name: string,
    description: string,
    img: string,
    totalPledged: bigint,
    createdAt: bigint,
    rewardToken: string,
    closed: boolean,
    config: string
  ] & {
    id: bigint;
    creator: string;
    name: string;
    description: string;
    img: string;
    totalPledged: bigint;
    createdAt: bigint;
    rewardToken: string;
    closed: boolean;
    config: string;
  };

  export type UserTaskStatusStruct = {
    taskId: BigNumberish;
    submitted: boolean;
    status: BigNumberish;
    submittedAt: BigNumberish;
    submitProof: string;
    reviewComment: string;
  };

  export type UserTaskStatusStructOutput = [
    taskId: bigint,
    submitted: boolean,
    status: bigint,
    submittedAt: bigint,
    submitProof: string,
    reviewComment: string
  ] & {
    taskId: bigint;
    submitted: boolean;
    status: bigint;
    submittedAt: bigint;
    submitProof: string;
    reviewComment: string;
  };

  export type BoardDetailViewStruct = {
    id: BigNumberish;
    creator: AddressLike;
    name: string;
    description: string;
    img: string;
    totalPledged: BigNumberish;
    createdAt: BigNumberish;
    closed: boolean;
    rewardToken: AddressLike;
    tasks: BoardStorage.TaskStruct[];
    members: AddressLike[];
    submissions: BoardStorage.SubmissionStruct[][];
    userTaskStatuses: BoardView.UserTaskStatusStruct[];
    config: string;
  };

  export type BoardDetailViewStructOutput = [
    id: bigint,
    creator: string,
    name: string,
    description: string,
    img: string,
    totalPledged: bigint,
    createdAt: bigint,
    closed: boolean,
    rewardToken: string,
    tasks: BoardStorage.TaskStructOutput[],
    members: string[],
    submissions: BoardStorage.SubmissionStructOutput[][],
    userTaskStatuses: BoardView.UserTaskStatusStructOutput[],
    config: string
  ] & {
    id: bigint;
    creator: string;
    name: string;
    description: string;
    img: string;
    totalPledged: bigint;
    createdAt: bigint;
    closed: boolean;
    rewardToken: string;
    tasks: BoardStorage.TaskStructOutput[];
    members: string[];
    submissions: BoardStorage.SubmissionStructOutput[][];
    userTaskStatuses: BoardView.UserTaskStatusStructOutput[];
    config: string;
  };
}

export declare namespace BoardStorage {
  export type TaskStruct = {
    id: BigNumberish;
    name: string;
    creator: AddressLike;
    description: string;
    deadline: BigNumberish;
    maxCompletions: BigNumberish;
    numCompletions: BigNumberish;
    reviewers: AddressLike[];
    completed: boolean;
    rewardAmount: BigNumberish;
    createdAt: BigNumberish;
    cancelled: boolean;
    config: string;
    allowSelfCheck: boolean;
  };

  export type TaskStructOutput = [
    id: bigint,
    name: string,
    creator: string,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    numCompletions: bigint,
    reviewers: string[],
    completed: boolean,
    rewardAmount: bigint,
    createdAt: bigint,
    cancelled: boolean,
    config: string,
    allowSelfCheck: boolean
  ] & {
    id: bigint;
    name: string;
    creator: string;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    numCompletions: bigint;
    reviewers: string[];
    completed: boolean;
    rewardAmount: bigint;
    createdAt: bigint;
    cancelled: boolean;
    config: string;
    allowSelfCheck: boolean;
  };

  export type SubmissionStruct = {
    submitter: AddressLike;
    proof: string;
    status: BigNumberish;
    submittedAt: BigNumberish;
    reviewComment: string;
  };

  export type SubmissionStructOutput = [
    submitter: string,
    proof: string,
    status: bigint,
    submittedAt: bigint,
    reviewComment: string
  ] & {
    submitter: string;
    proof: string;
    status: bigint;
    submittedAt: bigint;
    reviewComment: string;
  };
}

export interface BoardViewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "boardCount"
      | "boards"
      | "bountySubmissions"
      | "getAllBoards"
      | "getBoardDetail"
      | "getBoardsByMember"
      | "isBoardMember"
      | "signerAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "boardCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "boards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountySubmissions",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllBoards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBoardDetail",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBoardsByMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBoardMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "boardCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountySubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllBoards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoardDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoardsByMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBoardMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
}

export interface BoardView extends BaseContract {
  connect(runner?: ContractRunner | null): BoardView;
  waitForDeployment(): Promise<this>;

  interface: BoardViewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  boardCount: TypedContractMethod<[], [bigint], "view">;

  boards: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;

  bountySubmissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;

  getAllBoards: TypedContractMethod<
    [],
    [BoardView.BoardViewStructStructOutput[]],
    "view"
  >;

  getBoardDetail: TypedContractMethod<
    [_boardId: BigNumberish],
    [BoardView.BoardDetailViewStructOutput],
    "view"
  >;

  getBoardsByMember: TypedContractMethod<
    [_member: AddressLike],
    [BoardView.BoardViewStructStructOutput[]],
    "view"
  >;

  isBoardMember: TypedContractMethod<
    [_boardId: BigNumberish, _member: AddressLike],
    [boolean],
    "view"
  >;

  signerAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "boardCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "boards"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountySubmissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllBoards"
  ): TypedContractMethod<[], [BoardView.BoardViewStructStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getBoardDetail"
  ): TypedContractMethod<
    [_boardId: BigNumberish],
    [BoardView.BoardDetailViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBoardsByMember"
  ): TypedContractMethod<
    [_member: AddressLike],
    [BoardView.BoardViewStructStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBoardMember"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _member: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "signerAddress"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
