/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bountyBoardoldSol from "./BountyBoardold.sol";
export type { bountyBoardoldSol };
export type { BoardStorage } from "./BoardStorage";
export type { BoardView } from "./BoardView";
export type { BountyBoard } from "./BountyBoard";
export type { MockERC20 } from "./MockERC20";
export type { SubmissionManager } from "./SubmissionManager";
export type { TaskManager } from "./TaskManager";
export type { UserProfile } from "./UserProfile";
