/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TaskManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReviewerToTask"
      | "boardCount"
      | "boards"
      | "bountySubmissions"
      | "cancelTask"
      | "createTask"
      | "signerAddress"
      | "updateTask"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ReviewerAdded"
      | "TaskCancelled"
      | "TaskCreated"
      | "TaskUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReviewerToTask",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "boardCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "boards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountySubmissions",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateTask",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      boolean
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addReviewerToTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "boardCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountySubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTask", data: BytesLike): Result;
}

export namespace ReviewerAddedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    bountyId: BigNumberish,
    reviewer: AddressLike
  ];
  export type OutputTuple = [
    boardId: bigint,
    bountyId: bigint,
    reviewer: string
  ];
  export interface OutputObject {
    boardId: bigint;
    bountyId: bigint;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [boardId: BigNumberish, taskId: BigNumberish];
  export type OutputTuple = [boardId: bigint, taskId: bigint];
  export interface OutputObject {
    boardId: bigint;
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    taskId: BigNumberish,
    creator: AddressLike,
    name: string,
    description: string,
    deadline: BigNumberish,
    maxCompletions: BigNumberish,
    rewardAmount: BigNumberish,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    boardId: bigint,
    taskId: bigint,
    creator: string,
    name: string,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    rewardAmount: bigint,
    createdAt: bigint
  ];
  export interface OutputObject {
    boardId: bigint;
    taskId: bigint;
    creator: string;
    name: string;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    rewardAmount: bigint;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskUpdatedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    taskId: BigNumberish,
    name: string,
    description: string,
    deadline: BigNumberish,
    maxCompletions: BigNumberish,
    rewardAmount: BigNumberish,
    config: string,
    allowSelfCheck: boolean
  ];
  export type OutputTuple = [
    boardId: bigint,
    taskId: bigint,
    name: string,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    rewardAmount: bigint,
    config: string,
    allowSelfCheck: boolean
  ];
  export interface OutputObject {
    boardId: bigint;
    taskId: bigint;
    name: string;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    rewardAmount: bigint;
    config: string;
    allowSelfCheck: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskManager extends BaseContract {
  connect(runner?: ContractRunner | null): TaskManager;
  waitForDeployment(): Promise<this>;

  interface: TaskManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReviewerToTask: TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish, _reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  boardCount: TypedContractMethod<[], [bigint], "view">;

  boards: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;

  bountySubmissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;

  cancelTask: TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      _boardId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;

  signerAddress: TypedContractMethod<[], [string], "view">;

  updateTask: TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReviewerToTask"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish, _reviewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "boardCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "boards"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountySubmissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      _boardId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateTask"
  ): TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReviewerAdded"
  ): TypedContractEvent<
    ReviewerAddedEvent.InputTuple,
    ReviewerAddedEvent.OutputTuple,
    ReviewerAddedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskUpdated"
  ): TypedContractEvent<
    TaskUpdatedEvent.InputTuple,
    TaskUpdatedEvent.OutputTuple,
    TaskUpdatedEvent.OutputObject
  >;

  filters: {
    "ReviewerAdded(uint256,uint256,address)": TypedContractEvent<
      ReviewerAddedEvent.InputTuple,
      ReviewerAddedEvent.OutputTuple,
      ReviewerAddedEvent.OutputObject
    >;
    ReviewerAdded: TypedContractEvent<
      ReviewerAddedEvent.InputTuple,
      ReviewerAddedEvent.OutputTuple,
      ReviewerAddedEvent.OutputObject
    >;

    "TaskCancelled(uint256,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCreated(uint256,uint256,address,string,string,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskUpdated(uint256,uint256,string,string,uint256,uint256,uint256,string,bool)": TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;
    TaskUpdated: TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;
  };
}
