/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BountyBoard {
  export type BoardViewStruct = {
    id: BigNumberish;
    creator: AddressLike;
    name: string;
    description: string;
    img: string;
    totalPledged: BigNumberish;
    createdAt: BigNumberish;
    rewardToken: AddressLike;
    closed: boolean;
    config: string;
  };

  export type BoardViewStructOutput = [
    id: bigint,
    creator: string,
    name: string,
    description: string,
    img: string,
    totalPledged: bigint,
    createdAt: bigint,
    rewardToken: string,
    closed: boolean,
    config: string
  ] & {
    id: bigint;
    creator: string;
    name: string;
    description: string;
    img: string;
    totalPledged: bigint;
    createdAt: bigint;
    rewardToken: string;
    closed: boolean;
    config: string;
  };

  export type TaskViewStruct = {
    id: BigNumberish;
    name: string;
    creator: AddressLike;
    description: string;
    deadline: BigNumberish;
    maxCompletions: BigNumberish;
    numCompletions: BigNumberish;
    completed: boolean;
    rewardAmount: BigNumberish;
    createdAt: BigNumberish;
    cancelled: boolean;
    reviewers: AddressLike[];
    config: string;
    allowSelfCheck: boolean;
  };

  export type TaskViewStructOutput = [
    id: bigint,
    name: string,
    creator: string,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    numCompletions: bigint,
    completed: boolean,
    rewardAmount: bigint,
    createdAt: bigint,
    cancelled: boolean,
    reviewers: string[],
    config: string,
    allowSelfCheck: boolean
  ] & {
    id: bigint;
    name: string;
    creator: string;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    numCompletions: bigint;
    completed: boolean;
    rewardAmount: bigint;
    createdAt: bigint;
    cancelled: boolean;
    reviewers: string[];
    config: string;
    allowSelfCheck: boolean;
  };

  export type SubmissionViewStruct = {
    taskId: BigNumberish;
    submitter: AddressLike;
    proof: string;
    status: BigNumberish;
    submittedAt: BigNumberish;
    reviewComment: string;
  };

  export type SubmissionViewStructOutput = [
    taskId: bigint,
    submitter: string,
    proof: string,
    status: bigint,
    submittedAt: bigint,
    reviewComment: string
  ] & {
    taskId: bigint;
    submitter: string;
    proof: string;
    status: bigint;
    submittedAt: bigint;
    reviewComment: string;
  };

  export type UserTaskStatusStruct = {
    taskId: BigNumberish;
    submitted: boolean;
    status: BigNumberish;
    submittedAt: BigNumberish;
    submitProof: string;
    reviewComment: string;
  };

  export type UserTaskStatusStructOutput = [
    taskId: bigint,
    submitted: boolean,
    status: bigint,
    submittedAt: bigint,
    submitProof: string,
    reviewComment: string
  ] & {
    taskId: bigint;
    submitted: boolean;
    status: bigint;
    submittedAt: bigint;
    submitProof: string;
    reviewComment: string;
  };

  export type BoardDetailViewStruct = {
    currentUser: AddressLike;
    id: BigNumberish;
    creator: AddressLike;
    name: string;
    description: string;
    img: string;
    totalPledged: BigNumberish;
    createdAt: BigNumberish;
    closed: boolean;
    rewardToken: AddressLike;
    tasks: BountyBoard.TaskViewStruct[];
    submissions: BountyBoard.SubmissionViewStruct[];
    members: AddressLike[];
    userTaskStatuses: BountyBoard.UserTaskStatusStruct[];
    config: string;
  };

  export type BoardDetailViewStructOutput = [
    currentUser: string,
    id: bigint,
    creator: string,
    name: string,
    description: string,
    img: string,
    totalPledged: bigint,
    createdAt: bigint,
    closed: boolean,
    rewardToken: string,
    tasks: BountyBoard.TaskViewStructOutput[],
    submissions: BountyBoard.SubmissionViewStructOutput[],
    members: string[],
    userTaskStatuses: BountyBoard.UserTaskStatusStructOutput[],
    config: string
  ] & {
    currentUser: string;
    id: bigint;
    creator: string;
    name: string;
    description: string;
    img: string;
    totalPledged: bigint;
    createdAt: bigint;
    closed: boolean;
    rewardToken: string;
    tasks: BountyBoard.TaskViewStructOutput[];
    submissions: BountyBoard.SubmissionViewStructOutput[];
    members: string[];
    userTaskStatuses: BountyBoard.UserTaskStatusStructOutput[];
    config: string;
  };

  export type TaskDetailViewStruct = {
    id: BigNumberish;
    name: string;
    creator: AddressLike;
    description: string;
    deadline: BigNumberish;
    maxCompletions: BigNumberish;
    numCompletions: BigNumberish;
    completed: boolean;
    rewardAmount: BigNumberish;
    createdAt: BigNumberish;
    cancelled: boolean;
    config: string;
    allowSelfCheck: boolean;
  };

  export type TaskDetailViewStructOutput = [
    id: bigint,
    name: string,
    creator: string,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    numCompletions: bigint,
    completed: boolean,
    rewardAmount: bigint,
    createdAt: bigint,
    cancelled: boolean,
    config: string,
    allowSelfCheck: boolean
  ] & {
    id: bigint;
    name: string;
    creator: string;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    numCompletions: bigint;
    completed: boolean;
    rewardAmount: bigint;
    createdAt: bigint;
    cancelled: boolean;
    config: string;
    allowSelfCheck: boolean;
  };
}

export interface BountyBoardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "REVIEWER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "addReviewerToTask"
      | "boardCount"
      | "boards"
      | "bountySubmissions"
      | "cancelTask"
      | "closeBoard"
      | "createBountyBoard"
      | "createTask"
      | "getAllBoards"
      | "getBoardDetail"
      | "getBoardsByMember"
      | "getRoleAdmin"
      | "getTaskDetail"
      | "getTasksForBoard"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isBoardMember"
      | "joinBoard"
      | "pledgeTokens"
      | "proxiableUUID"
      | "renounceRole"
      | "reviewSubmission"
      | "revokeRole"
      | "selfCheckSubmission"
      | "setSignerAddress"
      | "signerAddress"
      | "submitProof"
      | "supportsInterface"
      | "updateBountyBoard"
      | "updateTask"
      | "upgradeToAndCall"
      | "withdrawPledgedTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyBoardClosed"
      | "BountyBoardCreated"
      | "BountyBoardUpdated"
      | "BountyCancelled"
      | "BountyUpdated"
      | "ContractUpgraded"
      | "Initialized"
      | "ReviewerAdded"
      | "RewardDistributionUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SubmissionMade"
      | "SubmissionReviewed"
      | "TaskCancelled"
      | "TaskCreated"
      | "TaskSucceeded"
      | "TaskUpdated"
      | "TokensPledged"
      | "TokensWithdrawn"
      | "Upgraded"
      | "UserJoinedBoard"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVIEWER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addReviewerToTask",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "boardCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "boards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountySubmissions",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeBoard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBountyBoard",
    values: [string, string, string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllBoards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBoardDetail",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBoardsByMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskDetail",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTasksForBoard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBoardMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinBoard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pledgeTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reviewSubmission",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "selfCheckSubmission",
    values: [BigNumberish, BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSignerAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBountyBoard",
    values: [BigNumberish, string, string, string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTask",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPledgedTokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVIEWER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addReviewerToTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "boardCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountySubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBountyBoard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllBoards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoardDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoardsByMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaskDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTasksForBoard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBoardMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pledgeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "selfCheckSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSignerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBountyBoard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPledgedTokens",
    data: BytesLike
  ): Result;
}

export namespace BountyBoardClosedEvent {
  export type InputTuple = [boardId: BigNumberish];
  export type OutputTuple = [boardId: bigint];
  export interface OutputObject {
    boardId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyBoardCreatedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    creator: AddressLike,
    name: string,
    description: string,
    rewardToken: AddressLike,
    createdAt: BigNumberish,
    config: string
  ];
  export type OutputTuple = [
    boardId: bigint,
    creator: string,
    name: string,
    description: string,
    rewardToken: string,
    createdAt: bigint,
    config: string
  ];
  export interface OutputObject {
    boardId: bigint;
    creator: string;
    name: string;
    description: string;
    rewardToken: string;
    createdAt: bigint;
    config: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyBoardUpdatedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    name: string,
    description: string,
    rewardToken: AddressLike,
    config: string
  ];
  export type OutputTuple = [
    boardId: bigint,
    name: string,
    description: string,
    rewardToken: string,
    config: string
  ];
  export interface OutputObject {
    boardId: bigint;
    name: string;
    description: string;
    rewardToken: string;
    config: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [boardId: BigNumberish, bountyId: BigNumberish];
  export type OutputTuple = [boardId: bigint, bountyId: bigint];
  export interface OutputObject {
    boardId: bigint;
    bountyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyUpdatedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    bountyId: BigNumberish,
    description: string,
    deadline: BigNumberish,
    maxCompletions: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    boardId: bigint,
    bountyId: bigint,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    boardId: bigint;
    bountyId: bigint;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUpgradedEvent {
  export type InputTuple = [
    oldImplementation: AddressLike,
    newImplementation: AddressLike
  ];
  export type OutputTuple = [
    oldImplementation: string,
    newImplementation: string
  ];
  export interface OutputObject {
    oldImplementation: string;
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerAddedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    bountyId: BigNumberish,
    reviewer: AddressLike
  ];
  export type OutputTuple = [
    boardId: bigint,
    bountyId: bigint,
    reviewer: string
  ];
  export interface OutputObject {
    boardId: bigint;
    bountyId: bigint;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributionUpdatedEvent {
  export type InputTuple = [boardId: BigNumberish, totalPledged: BigNumberish];
  export type OutputTuple = [boardId: bigint, totalPledged: bigint];
  export interface OutputObject {
    boardId: bigint;
    totalPledged: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionMadeEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    bountyId: BigNumberish,
    submitter: AddressLike,
    proof: string,
    submittedAt: BigNumberish
  ];
  export type OutputTuple = [
    boardId: bigint,
    bountyId: bigint,
    submitter: string,
    proof: string,
    submittedAt: bigint
  ];
  export interface OutputObject {
    boardId: bigint;
    bountyId: bigint;
    submitter: string;
    proof: string;
    submittedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionReviewedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    bountyId: BigNumberish,
    reviewer: AddressLike,
    submitter: AddressLike,
    status: BigNumberish,
    reviewComment: string
  ];
  export type OutputTuple = [
    boardId: bigint,
    bountyId: bigint,
    reviewer: string,
    submitter: string,
    status: bigint,
    reviewComment: string
  ];
  export interface OutputObject {
    boardId: bigint;
    bountyId: bigint;
    reviewer: string;
    submitter: string;
    status: bigint;
    reviewComment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [boardId: BigNumberish, taskId: BigNumberish];
  export type OutputTuple = [boardId: bigint, taskId: bigint];
  export interface OutputObject {
    boardId: bigint;
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    taskId: BigNumberish,
    creator: AddressLike,
    name: string,
    description: string,
    deadline: BigNumberish,
    maxCompletions: BigNumberish,
    rewardAmount: BigNumberish,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    boardId: bigint,
    taskId: bigint,
    creator: string,
    name: string,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    rewardAmount: bigint,
    createdAt: bigint
  ];
  export interface OutputObject {
    boardId: bigint;
    taskId: bigint;
    creator: string;
    name: string;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    rewardAmount: bigint;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSucceededEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    taskId: BigNumberish,
    submitter: AddressLike,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    boardId: bigint,
    taskId: bigint,
    submitter: string,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    boardId: bigint;
    taskId: bigint;
    submitter: string;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskUpdatedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    taskId: BigNumberish,
    name: string,
    description: string,
    deadline: BigNumberish,
    maxCompletions: BigNumberish,
    rewardAmount: BigNumberish,
    config: string,
    allowSelfCheck: boolean
  ];
  export type OutputTuple = [
    boardId: bigint,
    taskId: bigint,
    name: string,
    description: string,
    deadline: bigint,
    maxCompletions: bigint,
    rewardAmount: bigint,
    config: string,
    allowSelfCheck: boolean
  ];
  export interface OutputObject {
    boardId: bigint;
    taskId: bigint;
    name: string;
    description: string;
    deadline: bigint;
    maxCompletions: bigint;
    rewardAmount: bigint;
    config: string;
    allowSelfCheck: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPledgedEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    pledger: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [boardId: bigint, pledger: string, amount: bigint];
  export interface OutputObject {
    boardId: bigint;
    pledger: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensWithdrawnEvent {
  export type InputTuple = [
    boardId: BigNumberish,
    withdrawer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    boardId: bigint,
    withdrawer: string,
    amount: bigint
  ];
  export interface OutputObject {
    boardId: bigint;
    withdrawer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserJoinedBoardEvent {
  export type InputTuple = [boardId: BigNumberish, user: AddressLike];
  export type OutputTuple = [boardId: bigint, user: string];
  export interface OutputObject {
    boardId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BountyBoard extends BaseContract {
  connect(runner?: ContractRunner | null): BountyBoard;
  waitForDeployment(): Promise<this>;

  interface: BountyBoardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  REVIEWER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addReviewerToTask: TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish, _reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  boardCount: TypedContractMethod<[], [bigint], "view">;

  boards: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;

  bountySubmissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;

  cancelTask: TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeBoard: TypedContractMethod<
    [_boardId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBountyBoard: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _img: string,
      _rewardToken: AddressLike,
      _config: string
    ],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      _boardId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;

  getAllBoards: TypedContractMethod<
    [],
    [BountyBoard.BoardViewStructOutput[]],
    "view"
  >;

  getBoardDetail: TypedContractMethod<
    [_boardId: BigNumberish],
    [BountyBoard.BoardDetailViewStructOutput],
    "view"
  >;

  getBoardsByMember: TypedContractMethod<
    [_member: AddressLike],
    [BountyBoard.BoardViewStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTaskDetail: TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish],
    [BountyBoard.TaskDetailViewStructOutput],
    "view"
  >;

  getTasksForBoard: TypedContractMethod<
    [_boardId: BigNumberish],
    [BountyBoard.TaskViewStructOutput[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_signerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  isBoardMember: TypedContractMethod<
    [_boardId: BigNumberish, _member: AddressLike],
    [boolean],
    "view"
  >;

  joinBoard: TypedContractMethod<
    [_boardId: BigNumberish],
    [void],
    "nonpayable"
  >;

  pledgeTokens: TypedContractMethod<
    [_boardId: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  reviewSubmission: TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _submitter: AddressLike,
      _status: BigNumberish,
      _reviewComment: string
    ],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  selfCheckSubmission: TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _signature: BytesLike,
      _checkData: string
    ],
    [void],
    "nonpayable"
  >;

  setSignerAddress: TypedContractMethod<
    [_newSignerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  signerAddress: TypedContractMethod<[], [string], "view">;

  submitProof: TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish, _proof: string],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateBountyBoard: TypedContractMethod<
    [
      _boardId: BigNumberish,
      _name: string,
      _description: string,
      _img: string,
      _rewardToken: AddressLike,
      _config: string
    ],
    [void],
    "nonpayable"
  >;

  updateTask: TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdrawPledgedTokens: TypedContractMethod<
    [_boardId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REVIEWER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addReviewerToTask"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish, _reviewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "boardCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "boards"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        img: string;
        rewardToken: string;
        totalPledged: bigint;
        createdAt: bigint;
        closed: boolean;
        config: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountySubmissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        submitter: string;
        proof: string;
        status: bigint;
        submittedAt: bigint;
        reviewComment: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeBoard"
  ): TypedContractMethod<[_boardId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBountyBoard"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _img: string,
      _rewardToken: AddressLike,
      _config: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      _boardId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllBoards"
  ): TypedContractMethod<[], [BountyBoard.BoardViewStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getBoardDetail"
  ): TypedContractMethod<
    [_boardId: BigNumberish],
    [BountyBoard.BoardDetailViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBoardsByMember"
  ): TypedContractMethod<
    [_member: AddressLike],
    [BountyBoard.BoardViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTaskDetail"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish],
    [BountyBoard.TaskDetailViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTasksForBoard"
  ): TypedContractMethod<
    [_boardId: BigNumberish],
    [BountyBoard.TaskViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[_signerAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isBoardMember"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _member: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinBoard"
  ): TypedContractMethod<[_boardId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pledgeTokens"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reviewSubmission"
  ): TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _submitter: AddressLike,
      _status: BigNumberish,
      _reviewComment: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "selfCheckSubmission"
  ): TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _signature: BytesLike,
      _checkData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSignerAddress"
  ): TypedContractMethod<
    [_newSignerAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [_boardId: BigNumberish, _taskId: BigNumberish, _proof: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateBountyBoard"
  ): TypedContractMethod<
    [
      _boardId: BigNumberish,
      _name: string,
      _description: string,
      _img: string,
      _rewardToken: AddressLike,
      _config: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTask"
  ): TypedContractMethod<
    [
      _boardId: BigNumberish,
      _taskId: BigNumberish,
      _name: string,
      _description: string,
      _deadline: BigNumberish,
      _maxCompletions: BigNumberish,
      _rewardAmount: BigNumberish,
      _config: string,
      _allowSelfCheck: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawPledgedTokens"
  ): TypedContractMethod<[_boardId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BountyBoardClosed"
  ): TypedContractEvent<
    BountyBoardClosedEvent.InputTuple,
    BountyBoardClosedEvent.OutputTuple,
    BountyBoardClosedEvent.OutputObject
  >;
  getEvent(
    key: "BountyBoardCreated"
  ): TypedContractEvent<
    BountyBoardCreatedEvent.InputTuple,
    BountyBoardCreatedEvent.OutputTuple,
    BountyBoardCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BountyBoardUpdated"
  ): TypedContractEvent<
    BountyBoardUpdatedEvent.InputTuple,
    BountyBoardUpdatedEvent.OutputTuple,
    BountyBoardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyUpdated"
  ): TypedContractEvent<
    BountyUpdatedEvent.InputTuple,
    BountyUpdatedEvent.OutputTuple,
    BountyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUpgraded"
  ): TypedContractEvent<
    ContractUpgradedEvent.InputTuple,
    ContractUpgradedEvent.OutputTuple,
    ContractUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerAdded"
  ): TypedContractEvent<
    ReviewerAddedEvent.InputTuple,
    ReviewerAddedEvent.OutputTuple,
    ReviewerAddedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributionUpdated"
  ): TypedContractEvent<
    RewardDistributionUpdatedEvent.InputTuple,
    RewardDistributionUpdatedEvent.OutputTuple,
    RewardDistributionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionMade"
  ): TypedContractEvent<
    SubmissionMadeEvent.InputTuple,
    SubmissionMadeEvent.OutputTuple,
    SubmissionMadeEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionReviewed"
  ): TypedContractEvent<
    SubmissionReviewedEvent.InputTuple,
    SubmissionReviewedEvent.OutputTuple,
    SubmissionReviewedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskSucceeded"
  ): TypedContractEvent<
    TaskSucceededEvent.InputTuple,
    TaskSucceededEvent.OutputTuple,
    TaskSucceededEvent.OutputObject
  >;
  getEvent(
    key: "TaskUpdated"
  ): TypedContractEvent<
    TaskUpdatedEvent.InputTuple,
    TaskUpdatedEvent.OutputTuple,
    TaskUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPledged"
  ): TypedContractEvent<
    TokensPledgedEvent.InputTuple,
    TokensPledgedEvent.OutputTuple,
    TokensPledgedEvent.OutputObject
  >;
  getEvent(
    key: "TokensWithdrawn"
  ): TypedContractEvent<
    TokensWithdrawnEvent.InputTuple,
    TokensWithdrawnEvent.OutputTuple,
    TokensWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "UserJoinedBoard"
  ): TypedContractEvent<
    UserJoinedBoardEvent.InputTuple,
    UserJoinedBoardEvent.OutputTuple,
    UserJoinedBoardEvent.OutputObject
  >;

  filters: {
    "BountyBoardClosed(uint256)": TypedContractEvent<
      BountyBoardClosedEvent.InputTuple,
      BountyBoardClosedEvent.OutputTuple,
      BountyBoardClosedEvent.OutputObject
    >;
    BountyBoardClosed: TypedContractEvent<
      BountyBoardClosedEvent.InputTuple,
      BountyBoardClosedEvent.OutputTuple,
      BountyBoardClosedEvent.OutputObject
    >;

    "BountyBoardCreated(uint256,address,string,string,address,uint256,string)": TypedContractEvent<
      BountyBoardCreatedEvent.InputTuple,
      BountyBoardCreatedEvent.OutputTuple,
      BountyBoardCreatedEvent.OutputObject
    >;
    BountyBoardCreated: TypedContractEvent<
      BountyBoardCreatedEvent.InputTuple,
      BountyBoardCreatedEvent.OutputTuple,
      BountyBoardCreatedEvent.OutputObject
    >;

    "BountyBoardUpdated(uint256,string,string,address,string)": TypedContractEvent<
      BountyBoardUpdatedEvent.InputTuple,
      BountyBoardUpdatedEvent.OutputTuple,
      BountyBoardUpdatedEvent.OutputObject
    >;
    BountyBoardUpdated: TypedContractEvent<
      BountyBoardUpdatedEvent.InputTuple,
      BountyBoardUpdatedEvent.OutputTuple,
      BountyBoardUpdatedEvent.OutputObject
    >;

    "BountyCancelled(uint256,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyUpdated(uint256,uint256,string,uint256,uint256,uint256)": TypedContractEvent<
      BountyUpdatedEvent.InputTuple,
      BountyUpdatedEvent.OutputTuple,
      BountyUpdatedEvent.OutputObject
    >;
    BountyUpdated: TypedContractEvent<
      BountyUpdatedEvent.InputTuple,
      BountyUpdatedEvent.OutputTuple,
      BountyUpdatedEvent.OutputObject
    >;

    "ContractUpgraded(address,address)": TypedContractEvent<
      ContractUpgradedEvent.InputTuple,
      ContractUpgradedEvent.OutputTuple,
      ContractUpgradedEvent.OutputObject
    >;
    ContractUpgraded: TypedContractEvent<
      ContractUpgradedEvent.InputTuple,
      ContractUpgradedEvent.OutputTuple,
      ContractUpgradedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "ReviewerAdded(uint256,uint256,address)": TypedContractEvent<
      ReviewerAddedEvent.InputTuple,
      ReviewerAddedEvent.OutputTuple,
      ReviewerAddedEvent.OutputObject
    >;
    ReviewerAdded: TypedContractEvent<
      ReviewerAddedEvent.InputTuple,
      ReviewerAddedEvent.OutputTuple,
      ReviewerAddedEvent.OutputObject
    >;

    "RewardDistributionUpdated(uint256,uint256)": TypedContractEvent<
      RewardDistributionUpdatedEvent.InputTuple,
      RewardDistributionUpdatedEvent.OutputTuple,
      RewardDistributionUpdatedEvent.OutputObject
    >;
    RewardDistributionUpdated: TypedContractEvent<
      RewardDistributionUpdatedEvent.InputTuple,
      RewardDistributionUpdatedEvent.OutputTuple,
      RewardDistributionUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SubmissionMade(uint256,uint256,address,string,uint256)": TypedContractEvent<
      SubmissionMadeEvent.InputTuple,
      SubmissionMadeEvent.OutputTuple,
      SubmissionMadeEvent.OutputObject
    >;
    SubmissionMade: TypedContractEvent<
      SubmissionMadeEvent.InputTuple,
      SubmissionMadeEvent.OutputTuple,
      SubmissionMadeEvent.OutputObject
    >;

    "SubmissionReviewed(uint256,uint256,address,address,int8,string)": TypedContractEvent<
      SubmissionReviewedEvent.InputTuple,
      SubmissionReviewedEvent.OutputTuple,
      SubmissionReviewedEvent.OutputObject
    >;
    SubmissionReviewed: TypedContractEvent<
      SubmissionReviewedEvent.InputTuple,
      SubmissionReviewedEvent.OutputTuple,
      SubmissionReviewedEvent.OutputObject
    >;

    "TaskCancelled(uint256,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCreated(uint256,uint256,address,string,string,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskSucceeded(uint256,uint256,address,uint256)": TypedContractEvent<
      TaskSucceededEvent.InputTuple,
      TaskSucceededEvent.OutputTuple,
      TaskSucceededEvent.OutputObject
    >;
    TaskSucceeded: TypedContractEvent<
      TaskSucceededEvent.InputTuple,
      TaskSucceededEvent.OutputTuple,
      TaskSucceededEvent.OutputObject
    >;

    "TaskUpdated(uint256,uint256,string,string,uint256,uint256,uint256,string,bool)": TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;
    TaskUpdated: TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;

    "TokensPledged(uint256,address,uint256)": TypedContractEvent<
      TokensPledgedEvent.InputTuple,
      TokensPledgedEvent.OutputTuple,
      TokensPledgedEvent.OutputObject
    >;
    TokensPledged: TypedContractEvent<
      TokensPledgedEvent.InputTuple,
      TokensPledgedEvent.OutputTuple,
      TokensPledgedEvent.OutputObject
    >;

    "TokensWithdrawn(uint256,address,uint256)": TypedContractEvent<
      TokensWithdrawnEvent.InputTuple,
      TokensWithdrawnEvent.OutputTuple,
      TokensWithdrawnEvent.OutputObject
    >;
    TokensWithdrawn: TypedContractEvent<
      TokensWithdrawnEvent.InputTuple,
      TokensWithdrawnEvent.OutputTuple,
      TokensWithdrawnEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "UserJoinedBoard(uint256,address)": TypedContractEvent<
      UserJoinedBoardEvent.InputTuple,
      UserJoinedBoardEvent.OutputTuple,
      UserJoinedBoardEvent.OutputObject
    >;
    UserJoinedBoard: TypedContractEvent<
      UserJoinedBoardEvent.InputTuple,
      UserJoinedBoardEvent.OutputTuple,
      UserJoinedBoardEvent.OutputObject
    >;
  };
}
