/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bountyBoardoldSol from "./BountyBoardold.sol";
export { BoardStorage__factory } from "./BoardStorage__factory";
export { BoardView__factory } from "./BoardView__factory";
export { BountyBoard__factory } from "./BountyBoard__factory";
export { MockERC20__factory } from "./MockERC20__factory";
export { SubmissionManager__factory } from "./SubmissionManager__factory";
export { TaskManager__factory } from "./TaskManager__factory";
export { UserProfile__factory } from "./UserProfile__factory";
